# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from hars_memory.grpc import hars_memory_pb2 as hars__memory__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hars_memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LongTermMemoryStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/hars_memory.LongTermMemory/Query',
                request_serializer=hars__memory__pb2.QueryRequest.SerializeToString,
                response_deserializer=hars__memory__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/hars_memory.LongTermMemory/Status',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=hars__memory__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Remember = channel.unary_unary(
                '/hars_memory.LongTermMemory/Remember',
                request_serializer=hars__memory__pb2.RememberRequest.SerializeToString,
                response_deserializer=hars__memory__pb2.RememberResponse.FromString,
                _registered_method=True)
        self.GetMemory = channel.unary_unary(
                '/hars_memory.LongTermMemory/GetMemory',
                request_serializer=hars__memory__pb2.GetMemoryRequest.SerializeToString,
                response_deserializer=hars__memory__pb2.GetMemoryResponse.FromString,
                _registered_method=True)
        self.ListMemories = channel.unary_unary(
                '/hars_memory.LongTermMemory/ListMemories',
                request_serializer=hars__memory__pb2.ListMemoriesRequest.SerializeToString,
                response_deserializer=hars__memory__pb2.ListMemoriesResponse.FromString,
                _registered_method=True)
        self.UpdateMemory = channel.unary_unary(
                '/hars_memory.LongTermMemory/UpdateMemory',
                request_serializer=hars__memory__pb2.UpdateMemoryRequest.SerializeToString,
                response_deserializer=hars__memory__pb2.UpdateMemoryResponse.FromString,
                _registered_method=True)
        self.DeleteMemory = channel.unary_unary(
                '/hars_memory.LongTermMemory/DeleteMemory',
                request_serializer=hars__memory__pb2.DeleteMemoryRequest.SerializeToString,
                response_deserializer=hars__memory__pb2.DeleteMemoryResponse.FromString,
                _registered_method=True)
        self.SearchEntities = channel.unary_unary(
                '/hars_memory.LongTermMemory/SearchEntities',
                request_serializer=hars__memory__pb2.EntitiesRequest.SerializeToString,
                response_deserializer=hars__memory__pb2.EntitiesResponse.FromString,
                _registered_method=True)
        self.RelatedEntities = channel.unary_unary(
                '/hars_memory.LongTermMemory/RelatedEntities',
                request_serializer=hars__memory__pb2.RelatedRequest.SerializeToString,
                response_deserializer=hars__memory__pb2.RelatedResponse.FromString,
                _registered_method=True)
        self.Consolidate = channel.unary_unary(
                '/hars_memory.LongTermMemory/Consolidate',
                request_serializer=hars__memory__pb2.ConsolidateRequest.SerializeToString,
                response_deserializer=hars__memory__pb2.ConsolidateResponse.FromString,
                _registered_method=True)
        self.Forget = channel.unary_unary(
                '/hars_memory.LongTermMemory/Forget',
                request_serializer=hars__memory__pb2.ForgetRequest.SerializeToString,
                response_deserializer=hars__memory__pb2.ForgetResponse.FromString,
                _registered_method=True)


class LongTermMemoryServicer:
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """Query the knowledge graph (equivalent to memory_recall MCP tool)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Index health (equivalent to memory_status MCP tool)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remember(self, request, context):
        """Save a note into staging (equivalent to memory_remember MCP tool)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemory(self, request, context):
        """Retrieve one catalogued memory by id or exact title.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMemories(self, request, context):
        """List catalogued memories with optional filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMemory(self, request, context):
        """Update one catalogued memory and reindex it when necessary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemory(self, request, context):
        """Delete one catalogued memory, retaining a tombstone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchEntities(self, request, context):
        """Search entities by name (equivalent to memory_entities MCP tool)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RelatedEntities(self, request, context):
        """N-hop subgraph traversal from an entity (equivalent to memory_related MCP tool)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consolidate(self, request, context):
        """Trigger incremental reindex (equivalent to memory_consolidate MCP tool)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forget(self, request, context):
        """Purge stale documents (equivalent to memory_forget MCP tool)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LongTermMemoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=hars__memory__pb2.QueryRequest.FromString,
                    response_serializer=hars__memory__pb2.QueryResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=hars__memory__pb2.StatusResponse.SerializeToString,
            ),
            'Remember': grpc.unary_unary_rpc_method_handler(
                    servicer.Remember,
                    request_deserializer=hars__memory__pb2.RememberRequest.FromString,
                    response_serializer=hars__memory__pb2.RememberResponse.SerializeToString,
            ),
            'GetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemory,
                    request_deserializer=hars__memory__pb2.GetMemoryRequest.FromString,
                    response_serializer=hars__memory__pb2.GetMemoryResponse.SerializeToString,
            ),
            'ListMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMemories,
                    request_deserializer=hars__memory__pb2.ListMemoriesRequest.FromString,
                    response_serializer=hars__memory__pb2.ListMemoriesResponse.SerializeToString,
            ),
            'UpdateMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMemory,
                    request_deserializer=hars__memory__pb2.UpdateMemoryRequest.FromString,
                    response_serializer=hars__memory__pb2.UpdateMemoryResponse.SerializeToString,
            ),
            'DeleteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemory,
                    request_deserializer=hars__memory__pb2.DeleteMemoryRequest.FromString,
                    response_serializer=hars__memory__pb2.DeleteMemoryResponse.SerializeToString,
            ),
            'SearchEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchEntities,
                    request_deserializer=hars__memory__pb2.EntitiesRequest.FromString,
                    response_serializer=hars__memory__pb2.EntitiesResponse.SerializeToString,
            ),
            'RelatedEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.RelatedEntities,
                    request_deserializer=hars__memory__pb2.RelatedRequest.FromString,
                    response_serializer=hars__memory__pb2.RelatedResponse.SerializeToString,
            ),
            'Consolidate': grpc.unary_unary_rpc_method_handler(
                    servicer.Consolidate,
                    request_deserializer=hars__memory__pb2.ConsolidateRequest.FromString,
                    response_serializer=hars__memory__pb2.ConsolidateResponse.SerializeToString,
            ),
            'Forget': grpc.unary_unary_rpc_method_handler(
                    servicer.Forget,
                    request_deserializer=hars__memory__pb2.ForgetRequest.FromString,
                    response_serializer=hars__memory__pb2.ForgetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hars_memory.LongTermMemory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hars_memory.LongTermMemory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LongTermMemory:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hars_memory.LongTermMemory/Query',
            hars__memory__pb2.QueryRequest.SerializeToString,
            hars__memory__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hars_memory.LongTermMemory/Status',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            hars__memory__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hars_memory.LongTermMemory/Remember',
            hars__memory__pb2.RememberRequest.SerializeToString,
            hars__memory__pb2.RememberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hars_memory.LongTermMemory/GetMemory',
            hars__memory__pb2.GetMemoryRequest.SerializeToString,
            hars__memory__pb2.GetMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hars_memory.LongTermMemory/ListMemories',
            hars__memory__pb2.ListMemoriesRequest.SerializeToString,
            hars__memory__pb2.ListMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hars_memory.LongTermMemory/UpdateMemory',
            hars__memory__pb2.UpdateMemoryRequest.SerializeToString,
            hars__memory__pb2.UpdateMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hars_memory.LongTermMemory/DeleteMemory',
            hars__memory__pb2.DeleteMemoryRequest.SerializeToString,
            hars__memory__pb2.DeleteMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hars_memory.LongTermMemory/SearchEntities',
            hars__memory__pb2.EntitiesRequest.SerializeToString,
            hars__memory__pb2.EntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RelatedEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hars_memory.LongTermMemory/RelatedEntities',
            hars__memory__pb2.RelatedRequest.SerializeToString,
            hars__memory__pb2.RelatedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consolidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hars_memory.LongTermMemory/Consolidate',
            hars__memory__pb2.ConsolidateRequest.SerializeToString,
            hars__memory__pb2.ConsolidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hars_memory.LongTermMemory/Forget',
            hars__memory__pb2.ForgetRequest.SerializeToString,
            hars__memory__pb2.ForgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
